# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/raviv/OneDrive/Desktop/FinalV/MODS123.xpr/MODS/MODS.cache/wt [current_project]
set_property parent.project_path C:/Users/raviv/OneDrive/Desktop/FinalV/MODS123.xpr/MODS/MODS.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/raviv/OneDrive/Desktop/FinalV/MODS123.xpr/MODS/MODS.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files C:/Users/raviv/OneDrive/Desktop/FinalV/MODS123.xpr/MODS/MODS.srcs/sources_1/imports/res/weights.coe
add_files C:/Users/raviv/OneDrive/Desktop/FinalV/MODS123.xpr/MODS/MODS.srcs/sources_1/imports/res/00.coe
read_verilog -library xil_defaultlib {
  C:/Users/raviv/OneDrive/Desktop/FinalV/MODS123.xpr/MODS/MODS.srcs/sources_1/new/D_Milestone.v
  C:/Users/raviv/OneDrive/Desktop/FinalV/MODS123.xpr/MODS/MODS.srcs/sources_1/new/Farm.v
  C:/Users/raviv/OneDrive/Desktop/FinalV/MODS123.xpr/MODS/MODS.srcs/sources_1/new/FishingTop.v
  C:/Users/raviv/OneDrive/Desktop/FinalV/MODS123.xpr/MODS/MODS.srcs/sources_1/new/Home.v
  C:/Users/raviv/OneDrive/Desktop/FinalV/MODS123.xpr/MODS/MODS.srcs/sources_1/new/Inventory.v
  C:/Users/raviv/OneDrive/Desktop/FinalV/MODS123.xpr/MODS/MODS.srcs/sources_1/new/MapMUX.v
  C:/Users/raviv/OneDrive/Desktop/FinalV/MODS123.xpr/MODS/MODS.srcs/sources_1/new/Movement.v
  C:/Users/raviv/OneDrive/Desktop/FinalV/MODS123.xpr/MODS/MODS.srcs/sources_1/imports/Desktop/Oled_Display.v
  C:/Users/raviv/OneDrive/Desktop/FinalV/MODS123.xpr/MODS/MODS.srcs/sources_1/new/flexible_clock.v
  C:/Users/raviv/OneDrive/Desktop/FinalV/MODS123.xpr/MODS/MODS.srcs/sources_1/new/my_char.v
  C:/Users/raviv/OneDrive/Desktop/FinalV/MODS123.xpr/MODS/MODS.srcs/sources_1/new/my_fishing_change_values.v
  C:/Users/raviv/OneDrive/Desktop/FinalV/MODS123.xpr/MODS/MODS.srcs/sources_1/new/my_fishing_control.v
  C:/Users/raviv/OneDrive/Desktop/FinalV/MODS123.xpr/MODS/MODS.srcs/sources_1/new/my_fishing_display1.v
  C:/Users/raviv/OneDrive/Desktop/FinalV/MODS123.xpr/MODS/MODS.srcs/sources_1/new/my_fishing_display2.v
  C:/Users/raviv/OneDrive/Desktop/FinalV/MODS123.xpr/MODS/MODS.srcs/sources_1/new/my_fishing_display3.v
  C:/Users/raviv/OneDrive/Desktop/FinalV/MODS123.xpr/MODS/MODS.srcs/sources_1/new/my_fishing_frame_counter.v
  C:/Users/raviv/OneDrive/Desktop/FinalV/MODS123.xpr/MODS/MODS.srcs/sources_1/new/my_fishing_movement.v
  C:/Users/raviv/OneDrive/Desktop/FinalV/MODS123.xpr/MODS/MODS.srcs/sources_1/new/my_fishing_sequence_counter.v
  C:/Users/raviv/OneDrive/Desktop/FinalV/MODS123.xpr/MODS/MODS.srcs/sources_1/new/my_lfsr_rng.v
  C:/Users/raviv/OneDrive/Desktop/FinalV/MODS123.xpr/MODS/MODS.srcs/sources_1/new/my_pushbutton_debouncer.v
  C:/Users/raviv/OneDrive/Desktop/FinalV/MODS123.xpr/MODS/MODS.srcs/sources_1/new/my_rgn_clock_mux.v
  C:/Users/raviv/OneDrive/Desktop/FinalV/MODS123.xpr/MODS/MODS.srcs/sources_1/new/my_winning_frame.v
  C:/Users/raviv/OneDrive/Desktop/FinalV/MODS123.xpr/MODS/MODS.srcs/sources_1/new/seven_seg.v
  C:/Users/raviv/OneDrive/Desktop/FinalV/MODS123.xpr/MODS/MODS.srcs/sources_1/new/Top_Student.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/raviv/OneDrive/Desktop/FinalV/MODS123.xpr/MODS/MODS.srcs/constrs_1/new/Basys_Constraints.xdc
set_property used_in_implementation false [get_files C:/Users/raviv/OneDrive/Desktop/FinalV/MODS123.xpr/MODS/MODS.srcs/constrs_1/new/Basys_Constraints.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top Top_Student -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Top_Student.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Top_Student_utilization_synth.rpt -pb Top_Student_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
